#!/bin/sh
#
# abook export script to sync abook & mutt/alias by armin wolfermann
abook --datafile $HOME/Sync/abook/addressbook ${@}
abook --convert \
	--informat abook --infile $HOME/Sync/abook/addressbook \
	--outformat mutt --outfile $HOME/.mutt/alias.new
mv $HOME/.mutt/alias $HOME/.mutt/alias.bak
mv $HOME/.mutt/alias.new $HOME/.mutt/alias

